CREATE TYPE "public"."store_status" AS ENUM('draft', 'active', 'suspended');--> statement-breakpoint
CREATE TABLE "stores" (
	"id" text PRIMARY KEY NOT NULL,
	"owner_id" text NOT NULL,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"tagline" text,
	"description" text NOT NULL,
	"contact_email" text NOT NULL,
	"contact_phone" text,
	"website" text,
	"business_type" text NOT NULL,
	"business_name" text NOT NULL,
	"tax_id" text,
	"address_line1" text NOT NULL,
	"city" text NOT NULL,
	"state" text NOT NULL,
	"zip_code" text NOT NULL,
	"country" text NOT NULL,
	"logo" text,
	"favicon" text,
	"primary_color" text NOT NULL,
	"secondary_color" text,
	"currency" text NOT NULL,
	"timezone" text NOT NULL,
	"language" text NOT NULL,
	"payment_methods" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"shipping_enabled" boolean DEFAULT true NOT NULL,
	"free_shipping_threshold" numeric,
	"shipping_rates" jsonb DEFAULT '[]'::jsonb,
	"terms_of_service" text NOT NULL,
	"privacy_policy" text NOT NULL,
	"refund_policy" text NOT NULL,
	"status" "store_status" DEFAULT 'draft' NOT NULL,
	"featured" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "stores_slug_unique" UNIQUE("slug")
);
