CREATE TYPE "public"."product_status" AS ENUM('draft', 'active', 'inactive', 'out_of_stock');--> statement-breakpoint
CREATE TYPE "public"."product_type" AS ENUM('physical', 'digital', 'service');--> statement-breakpoint
CREATE TABLE "products" (
	"id" text PRIMARY KEY NOT NULL,
	"store_id" text NOT NULL,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"description" text NOT NULL,
	"short_description" text,
	"sku" text,
	"type" "product_type" DEFAULT 'physical' NOT NULL,
	"status" "product_status" DEFAULT 'draft' NOT NULL,
	"price" numeric NOT NULL,
	"compare_at_price" numeric,
	"cost_price" numeric,
	"track_quantity" boolean DEFAULT true NOT NULL,
	"quantity" numeric DEFAULT '0' NOT NULL,
	"allow_backorder" boolean DEFAULT false NOT NULL,
	"weight" numeric,
	"length" numeric,
	"width" numeric,
	"height" numeric,
	"download_url" text,
	"download_expiry" numeric,
	"meta_title" text,
	"meta_description" text,
	"images" jsonb DEFAULT '[]'::jsonb,
	"variants" jsonb DEFAULT '[]'::jsonb,
	"categories" jsonb DEFAULT '[]'::jsonb,
	"tags" jsonb DEFAULT '[]'::jsonb,
	"featured" boolean DEFAULT false NOT NULL,
	"requires_shipping" boolean DEFAULT true NOT NULL,
	"taxable" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"published_at" timestamp with time zone
);
